export const OTHER_FETCH_USER_PROJECTS_REQUEST = 'OTHER_FETCH_USER_PROJECTS_REQUEST';
export const OTHER_FETCH_USER_PROJECTS_SUCCESS = 'OTHER_FETCH_USER_PROJECTS_SUCCESS';
export const OTHER_FETCH_USER_PROJECTS_FAILURE = 'OTHER_FETCH_USER_PROJECTS_FAILURE';