export const  CREATENEWPROJECTMODALREQ = 'CREATENEWPROJECTMODAL';
export const CREATENEWPROJECTMODALSUC = 'CREATENEWPROJECTMODALSUC';
export const CREATENEWPROJECTMODALERR = 'CREATENEWPROJECTMODALSUC';