export const FETCH_SINGLE_BUG_REQUEST = 'FETCH_SINGLE_BUG_REQUEST';
export const FETCH_SINGLE_BUG_SUCCESS = 'FETCH_SINGLE_BUG_SUCCESS';
export const FETCH_SINGLE_BUG_FAILURE = 'FETCH_SINGLE_BUG_FAILURE';