export const OTHER_FETCH_USER_TICKETS_REQUEST = 'OTHER_FETCH_USER_TICKETS_REQUEST';
export const OTHER_FETCH_USER_TICKETS_SUCCESS = 'OTHER_FETCH_USER_TICKETS_SUCCESS';
export const OTHER_FETCH_USER_TICKETS_FAILURE = 'OTHER_FETCH_USER_TICKETS_FAILURE';