export const FETCH_PENDING_TICKETS_REQUEST = 'FETCH_PENDING_TICKETS_REQUEST';
export const FETCH_PENDING_TICKETS_SUCCESS = 'FETCH_PENDING_TICKETS_SUCCESS';
export const FETCH_PENDING_TICKETS_FAILURE = 'FETCH_PENDING_TICKETS_FAILURE';