export const FETCH_USER_TICKETS_REQUEST = 'FETCH_USER_TICKETS_REQUEST';
export const FETCH_USER_TICKETS_SUCCESS = 'FETCH_USER_TICKETS_SUCCESS';
export const FETCH_USER_TICKETS_FAILURE = 'FETCH_USER_TICKETS_FAILURE';