export const FETCH_TICKETS_PRIORITY_REQUEST = 'FETCH_TICKETS_PRIORITY_REQUEST';
export const FETCH_TICKETS_PRIORITY_SUCCESS = 'FETCH_TICKETS_PRIORITY_SUCCESS';
export const FETCH_TICKETS_PRIORITY_FAILURE = 'FETCH_TICKETS_PRIORITY_FAILURE';