export const FETCH_TICKET_TYPES_REQUEST = 'FETCH_TICKET_TYPES_REQUEST';
export const FETCH_TICKET_TYPES_SUCCESS = 'FETCH_TICKET_TYPES_SUCCESS';
export const FETCH_TICKET_TYPES_FAILURE = 'FETCH_TICKET_TYPES_FAILURE';