export const ADD_USER_TO_PROJECT_REQUEST = 'ADD_USER_TO_PROJECT_REQUEST';
export const ADD_USER_TO_PROJECT_SUCCESS = 'ADD_USER_TO_PROJECT_SUCCESS';
export const ADD_USER_TO_PROJECT_FAILURE = 'ADD_USER_TO_PROJECT_FAILURE';