name: CI/CD Pipeline

on:
  push
    # branches:
      # - main
      # - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: executing remote ssh commands using password
        run: |
             ssh sibasi@172.191.145.106 && "bash -s" < ~/codeupdates.sh
             # SSH_PRIVATE_KEY: ${{ secrets.CICD_TEST }}
